"""user table

Revision ID: 667209c0d265
Revises: b16242e8271b
Create Date: 2022-09-20 18:26:56.571023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667209c0d265'
down_revision = 'b16242e8271b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
